allowBuilds:
  '@tlaplus/tree-sitter-tlaplus': true
  '@tree-sitter-grammars/tree-sitter-zig': true
  '@willjouo/tree-sitter-r': true
  tree-sitter-bash: true
  tree-sitter-c: true
  tree-sitter-c-sharp: true
  tree-sitter-cli: true
  tree-sitter-cpp: true
  tree-sitter-css: true
  tree-sitter-dart@https://codeload.github.com/UserNobody14/tree-sitter-dart/tar.gz/be07cf7118d3dba06236a3f19541685a68209934: true
  tree-sitter-elisp: true
  tree-sitter-elixir: true
  tree-sitter-elm: true
  tree-sitter-embedded-template: true
  tree-sitter-go: true
  tree-sitter-html: true
  tree-sitter-java: true
  tree-sitter-javascript: true
  tree-sitter-json: true
  tree-sitter-kotlin: true
  tree-sitter-lua: true
  tree-sitter-objc: true
  tree-sitter-ocaml: true
  tree-sitter-php: true
  tree-sitter-python: true
  tree-sitter-ql: true
  tree-sitter-ruby: true
  tree-sitter-rust: true
  tree-sitter-scala: true
  tree-sitter-solidity@https://codeload.github.com/JoranHonig/tree-sitter-solidity/tar.gz/b239a95f94cfcc6e7b3e961bc73a28d55e214f02: true
  tree-sitter-swift: true
  tree-sitter-systemrdl: true
  tree-sitter-toml: true
  tree-sitter-typescript: true
  tree-sitter-vue@https://codeload.github.com/tree-sitter-grammars/tree-sitter-vue/tar.gz/7e48557b903a9db9c38cea3b7839ef7e1f36c693: true
  tree-sitter-yaml: true
  yarn: true
minimumReleaseAgeExclude:
  - '@s-h-a-d-o-w/oxlint-config@1.5.0'
