name: build-and-publish
on:
  workflow_dispatch:
  push:
    tags: ["*"]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          cache: true
          runtime: node@lts

      # - uses: mymindstorm/setup-emsdk@v11
      #   with:
      #     version: 2.0.24

      - run: pnpm build
      # - run: pnpm publish --no-git-checks
