name: build-and-publish
on:
  push:
    tags: ["*"]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for npm provenance
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          cache: true
          runtime: node@lts
      - run: pnpm build
      - run: pnpm stage publish --no-git-checks
